apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-09-11T18:36:25Z"
  labels:
    run: cats
  name: cats-v2
  namespace: default
spec:
  containers:
  - image: mikesir87/cats:2.0
    imagePullPolicy: IfNotPresent
    name: cats
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5gfvs
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-5gfvs
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-09-11T18:36:25Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-09-11T18:36:26Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-09-11T18:36:26Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-09-11T18:36:25Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://6a05d1aa30404434fa3ae4cce783f3067b0f3361a14ca3341478d91eb8116b85
    image: mikesir87/cats:1.0
    imageID: docker-pullable://mikesir87/cats@sha256:0626e22be29d3084d880020fe6bddd16d8cf2b61cc6d8431ba431d69d61f6e75
    lastState: {}
    name: cats
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-09-11T18:36:26Z"
  hostIP: 192.168.65.4
  phase: Running
  podIP: 10.1.0.19
  podIPs:
  - ip: 10.1.0.19
  qosClass: BestEffort
  startTime: "2023-09-11T18:36:25Z"
---
apiVersion: v1
kind: Pod
metadata:
  name: cats-v3
spec:
  containers:
    - name: cats
      image: mikesir87/cats:3.0
